AddisTender/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_view
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('tenders/', include('tenders.urls')),
    path('register/', user_view.register, name = 'register' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'Login' ),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'Logout' ),  
    path('profile/', user_view.profile, name = 'profile' ),
    path('noti/', include('notifications.urls')),
    path('chat/', include('chat.urls')),
    path('payment/', include('payment.urls')), 

   
   
  
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, email
# from .views import detail
from django.urls import include

app_name = "Home"

urlpatterns = [
    path('', home, name = 'index'),
       path('email/', email, name = "email"),
]

about/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import about

app_name = "about"

urlpatterns = [
    path('', about, name = 'about'),
  
]

chat/urls.py
from django.urls import path
from chat.views import Inbox, UserSearch, Directs, NewConversation, SendDirect


app_name = "chat"

urlpatterns = [
   	path('', Inbox, name='inbox'),
   	path('directs/<username>', Directs, name='directs'),
   	path('new/', UserSearch, name='usersearch'),
   	path('new/<username>', NewConversation, name='newconversation'),
   	path('send/', SendDirect, name='send_direct'),

]

contact/urls.py
from django.contrib import admin
from django.urls import path
from .views import contact
# from .views import detail
from django.urls import include

app_name = "contact"

urlpatterns = [
    path('', contact, name = 'contact'),
]

tenders/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import (PostListView,PostDetailView
,PostCreateView,PostUpdateView,
PostDeleteView,UserPostListView,SearchPostListView,CategoryView, download)
from django.urls import include
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

app_name = "tenders"

urlpatterns = [   
    path('',  PostListView.as_view(), name = 'index'),
    path('user/<str:username>/',  UserPostListView.as_view(), name = 'user-posts'),
    path('<int:pk>', PostDetailView.as_view(), name = 'detail'),
    path('addnew', PostCreateView.as_view(), name ='addnew'),
    path('<int:pk>/update', PostUpdateView.as_view(), name ='update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name ='delete'),
    path('result', SearchPostListView.as_view(), name ='search'),
    path('<str:cats>', CategoryView, name='category'),
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Addis Tender | {{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700|Work+Sans:300,400,700" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'  %}">

  <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/mediaelementplayer.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css'%} ">

</head>

<body>

  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->


    <div class="site-navbar-wrap js-site-navbar bg-white">

      <div class="container">
        <div class="site-navbar bg-light">
          <div class="py-1">
            <div class="row align-items-center">
              <div class="col-2">
                <h2 class="mb-0 site-logo"><a href="{% url 'Home:index' %}">Addis<strong
                      class="font-weight-bold">Tender</strong>
                  </a></h2>
              </div>
              <div class="col-10">
                <nav class="site-navigation text-right" role="navigation">
                  <div class="container">
                    <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#"
                        class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>


                    {% if user.is_authenticated %}

                    <ul class="site-menu js-clone-nav d-none d-lg-block">
                      <button class="post"> <a href="{% url 'tenders:addnew' %}"> <span class="icon-plus mr-3"></span>
                          Post a Tender </a></button>
                         
                      <li class="material-icons"> home<a href="{% url 'Home:index' %}">home</a></li>
                  
                      <li class="material-icons">post_add<a href="{% url 'tenders:index' %}">Tenders</a></li>
                      <!--    <li><a href="#">Notification</a></li>-->
                      <!--       <li><a href="#">Message</a></li>-->

                      <li class="material-icons">notifications<a href="{% url 'notifications:show-notifications' %}">Notifications</a></li>
                      <li class="material-icons">message<a href="{% url 'chat:inbox' %}">Inbox</a></li>


                      <!-- <button type="button" class="btn btn-success" data-toggle="modal" data-target="#postModal">  <span class="icon-plus mr-3"></span></button>-->
                      <li class="has-children"> Howdy, <span style="color: teal;">{{user.username}}
                        </span>



                        <ul class="dropdown arrow-top">
                          <strong style="color: white;"> <img class="round-circle " src="{{user.profile.image.url}}">
                          </strong>
                     
                        <li><a href="{% url 'profile'  %}"> Edit Profile</a></li>
                        <li> <a href="{% url 'Logout'  %}">Log Out</a></li>
                        </ul>


                        {% else %}

                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                          <li><a href="{% url 'Home:index' %}">Home</a></li>
                          <li><a href="{% url 'about:about' %}">About us</a></li>
                          <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                          <li><a href="{% url 'Login'  %}"><span class="bg-primary text-white py-3 px-4 rounded">
                                Login</span></a></li>

                          <li><a href="{% url 'register' %}"><span class="bg-primary text-white py-3 px-4 rounded">
                                Register</span></a></li>
                          {% endif %}
                        </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="site-section">


      {% block content %}


      {% endblock %}
    </div>







    <footer class="site-footer">
      <div class="container">


        <div class="row">
          <div class="col-md-4">
            <h3 class="footer-heading mb-4 text-white">About</h3>
            <p>Addis Tender is your dedicated website that brings you tender information from all corners of the
              country. Here at Addis Tender, we understand that following tenders is hard,
              tiresome and requires time and sometimes it requires you hiring more staff dedicated for this job.</p>
            <p><a href="{% url 'about:about' %}" class="btn btn-primary pill text-white px-4">Read More</a></p>
          </div>
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-6">
                <h3 class="footer-heading mb-4 text-white">Quick Menu</h3>
                <ul class="list-unstyled">
                  <li><a href="{% url 'Home:index' %}">Home</a></li>
                  <li><a href="{% url 'about:about' %}">About</a></li>
                  <li><a href="{% url 'contact:contact' %}">Contact</a></li>

                </ul>
              </div>
              <div class="col-md-6">
                <h3 class="footer-heading mb-4 text-white">Categories</h3>
                <ul class="list-unstyled">
                  <li><a href="#">Accounting / Finanace</a></li>
                  <li><a href="#">Automotive Jobs</a></li>
                  <li><a href="#">Construction / Facilities</a></li>
                  <li><a href="#">Telecommunications</a></li>
                </ul>
              </div>
            </div>
          </div>


          <div class="col-md-2">
            <div class="col-md-12">
              <h3 class="footer-heading mb-4 text-white">Follow Us on</h3>
            </div>
            <div class="col-md-12">
              <p>
                <a href="facebook.com {{request.get_full_path|urlencode}}" class="pb-2 pr-2 pl-0"><span
                    class="icon-facebook"></span></a>
                <a href="google.com" class="p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="p-2"><span class="icon-instagram"></span></a>
                <a href="#" class="p-2"><span class="icon-vimeo"></span></a>

              </p>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script data-cfasync="false"
                src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
              <script>document.write(new Date().getFullYear());</script> All Rights Reserved | <i
                class="icon-heart text-warning" aria-hidden="true"></i> by <a href="{% url 'Home:index' %}"
                target="_blank">Addis Tender</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>

        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js'  %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>


  <script src="{% static 'js/mediaelement-and-player.min.js'  %}"></script>

  <script src=" {% static 'js/main.js'  %}"></script>


  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var mediaElements = document.querySelectorAll('video, audio'), total = mediaElements.length;

      for (var i = 0; i < total; i++) {
        new MediaElementPlayer(mediaElements[i], {
          pluginPath: 'https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/',
          shimScriptAccess: 'always',
          success: function () {
            var target = document.body.querySelectorAll('.player'), targetTotal = target.length;
            for (var j = 0; j < targetTotal; j++) {
              target[j].style.visibility = 'visible';
            }
          }
        });
      }
    });
  </script>


  <script>
    // This example displays an address form, using the autocomplete feature
    // of the Google Places API to help users fill in the information.

    // This example requires the Places library. Include the libraries=places
    // parameter when you first load the API. For example:
    // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

    var placeSearch, autocomplete;
    var componentForm = {
      street_number: 'short_name',
      route: 'long_name',
      locality: 'long_name',
      administrative_area_level_1: 'short_name',
      country: 'long_name',
      postal_code: 'short_name'
    };

    function initAutocomplete() {
      // Create the autocomplete object, restricting the search to geographical
      // location types.
      autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
        { types: ['geocode'] });

      // When the user selects an address from the dropdown, populate the address
      // fields in the form.
      autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
      // Get the place details from the autocomplete object.
      var place = autocomplete.getPlace();

      for (var component in componentForm) {
        document.getElementById(component).value = '';
        document.getElementById(component).disabled = false;
      }

      // Get each component of the address from the place details
      // and fill the corresponding field on the form.
      for (var i = 0; i < place.address_components.length; i++) {
        var addressType = place.address_components[i].types[0];
        if (componentForm[addressType]) {
          var val = place.address_components[i][componentForm[addressType]];
          document.getElementById(addressType).value = val;
        }
      }
    }

    // Bias the autocomplete object to the user's geographical location,
    // as supplied by the browser's 'navigator.geolocation' object.
    function geolocate() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function (position) {
          var geolocation = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };
          var circle = new google.maps.Circle({
            center: geolocation,
            radius: position.coords.accuracy
          });
          autocomplete.setBounds(circle.getBounds());
        });
      }
    }
  </script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&libraries=places&callback=initAutocomplete"
    async defer></script>

</body>

</html>