AddisTender/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_view
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('tenders/', include('tenders.urls')),
    path('register/', user_view.register, name = 'register' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'Login' ),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'Logout' ),  
    path('profile/', user_view.profile, name = 'profile' ),
    path('noti/', include('notifications.urls')),
    path('chat/', include('chat.urls')),
    path('payment/', include('payment.urls')), 

   
   
  
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, email
# from .views import detail
from django.urls import include

app_name = "Home"

urlpatterns = [
    path('', home, name = 'index'),
       path('email/', email, name = "email"),
]

chat/urls.py
from django.urls import path
from chat.views import Inbox, UserSearch, Directs, NewConversation, SendDirect


app_name = "chat"

urlpatterns = [
   	path('', Inbox, name='inbox'),
   	path('directs/<username>', Directs, name='directs'),
   	path('new/', UserSearch, name='usersearch'),
   	path('new/<username>', NewConversation, name='newconversation'),
   	path('send/', SendDirect, name='send_direct'),

]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Max

# Create your models here.
class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
	recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
	body = models.TextField(max_length=1000, blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	is_read = models.BooleanField(default=False)

	def send_message(from_user, to_user, body):
		sender_message = Message(
			user=from_user,
			sender=from_user,
			recipient=to_user,
			body=body,
			is_read=True)
		sender_message.save()

		recipient_message = Message(
			user=to_user,
			sender=from_user,
			body=body,
			recipient=from_user,)
		recipient_message.save()
		return sender_message

	def get_messages(user):
		messages = Message.objects.filter(user=user).values('recipient').annotate(last=Max('date')).order_by('-last')
		users = []
		for message in messages:
			users.append({
				'user': User.objects.get(pk=message['recipient']),
				'last': message['last'],
				'unread': Message.objects.filter(user=user, recipient__pk=message['recipient'], is_read=False).count()
				})
		return users

chat/views.py
from django.shortcuts import render, redirect
from django.template import loader, RequestContext
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from chat.models import Message


from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.

@login_required
def Inbox(request):
	messages = Message.get_messages(user=request.user)
	active_direct = None
	directs = None

	if messages:
		message = messages[0]
		active_direct = message['user'].username
		directs = Message.objects.filter(user=request.user, recipient=message['user'])
		directs.update(is_read=True)
		for message in messages:
			if message['user'].username == active_direct:
				message['unread'] = 0

	context = {
		'directs': directs,
		'messages': messages,
		'active_direct': active_direct,
		}

	template = loader.get_template('chat/index.html')

	return HttpResponse(template.render(context, request))

@login_required
def UserSearch(request):
	query = request.GET.get("q")
	context = {}
	
	if query:
		users = User.objects.filter(Q(username__icontains=query))

		#Pagination
		paginator = Paginator(users, 6)
		page_number = request.GET.get('page')
		users_paginator = paginator.get_page(page_number)

		context = {
				'users': users_paginator,
			}
	
	template = loader.get_template('chat/search_user.html')
	
	return HttpResponse(template.render(context, request))

@login_required
def Directs(request, username):
	user = request.user
	messages = Message.get_messages(user=user)
	active_direct = username
	directs = Message.objects.filter(user=user, recipient__username=username)
	directs.update(is_read=True)
	for message in messages:
		if message['user'].username == username:
			message['unread'] = 0

	context = {
		'directs': directs,
		'messages': messages,
		'active_direct':active_direct,
	}

	template = loader.get_template('chat/index.html')

	return HttpResponse(template.render(context, request))


@login_required
def NewConversation(request, username):
	from_user = request.user
	body = ''
	try:
		to_user = User.objects.get(username=username)
	except Exception as e:
		return redirect('usersearch')
	if from_user != to_user:
		Message.send_message(from_user, to_user, body)
	return redirect('chat:inbox')

@login_required
def SendDirect(request):
	from_user = request.user
	to_user_username = request.POST.get('to_user')
	body = request.POST.get('body')
	
	if request.method == 'POST':
		to_user = User.objects.get(username=to_user_username)
		Message.send_message(from_user, to_user, body)
		return redirect('chat:inbox')
	else:
		HttpResponseBadRequest()

def checkDirects(request):
	directs_count = 0
	if request.user.is_authenticated:
		directs_count = Message.objects.filter(user=request.user, is_read=False).count()

	return {'directs_count':directs_count}



	

templates/chat/index.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href= "{% static 'css/bulma.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css'%} ">





<div class="site-section bg-light">
  <div class="container">
<div class = "columns is-mobile is centered">


  <div class="columns is-one-quarter">


<aside class="menu">
  <h1 class="title is-2"> Message</h1>
  <ul style="overflow-y: scroll; height: 500px;" class="menu-list">

 
{% for message in messages %}
  <!--USER starts-->
  <a class="{% if active_direct == message.user.username %}is-active{% endif %}" href="{% url 'chat:directs' message.user.username %}">
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            {% if message.user.profile.picture %}
            <img src="{{ message.user.profile.image.url }}" alt="Placeholder image">
            {% else %}
            <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
            {% endif %}
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>@{{ message.user.username }}</strong> 
              
            </p>
          </div>
          <div class="content">
            {% if message.unread %}
            <p style="font-weight: bold; color: red;">
              <i class="material-icons">mark_chat_unread</i> {{ message.unread }}
            </p>
            {% endif %}        
          </div>
        </div>
      </article>
    </div>
  </a>
  {% endfor %}
    <!--USER ENDS-->

    
  </ul>
  <br>
  <a href="{% url 'chat:usersearch' %}"class = "button is-success">New Message</a>
</aside>

</div> 

<div class="column">
<div style="overflow-y: scroll; height: 500px;" >
  {% for direct in directs %}
  
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>@{{ direct.sender.username }}</strong> ----<small>{{ direct.date|date:'N d G:i'}}</small>
          <br>   {{ direct.body }} 
          </p>
        </div>
      
      </div>
    </article>
  </div>
  {% endfor %}
</div>


<form role="form" method="POST" action="{% url 'chat:send_direct' %}">
  {% csrf_token %}
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <input type="hidden" name="to_user" value="{{ active_direct }}">
    <div class="field">
      <p class="control">
        <textarea class="textarea" placeholder="send message..."></textarea>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
          <button type="submit" name="action" class="button is-info">Send</buttom>
        </div>
      </div>   
    </nav>
  </div>
</article>
</form>
</div>
</div>
</div>
</div>
{% endblock %}

templates/chat/search_user.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" href= "{% static 'css/bulma.min.css' %}">
 <div class="columns is-mobile">
  <div class="column is-offset-one-fifth">


<div class="field has-addons">
<form>
  <div class="control">
    <input class="input is-large" name="q" type="text" placeholder="Search users..." value="{{ request.GET.q }}">
  </div>
  <div class="control">
  	<button type="submit" class="button is-success">Search</button>
  </div>
  </form>
</div>


</div>
</div>

<div class="column is-one-quarter">

{% for user in users %}
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
          {% if user.profile.picture %}
            <img src="{{ user.profile.picture.url }}" alt="Placeholder image">
          {% else %}
            <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
          {% endif %}
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ user.profile.first_name }} {{ user.profile.last_name }}</strong><small>@{{ user.username }}</small>
        </p>
        <a href="{% url 'chat:newconversation' user.username %}" class="button is-info">Send a message!</a>
      </div>
    </div>
  </article>
</div>
{% endfor %}
	

</div>

{% endblock %}