AddisTender/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_view
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('tenders/', include('tenders.urls')),
    path('register/', user_view.register, name = 'register' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'Login' ),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'Logout' ),  
    path('profile/', user_view.profile, name = 'profile' ),
    path('noti/', include('notifications.urls')),
    path('chat/', include('chat.urls')),
    path('payment/', include('payment.urls')), 

   
   
  
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, email
# from .views import detail
from django.urls import include

app_name = "Home"

urlpatterns = [
    path('', home, name = 'index'),
       path('email/', email, name = "email"),
]

tenders/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import (PostListView,PostDetailView
,PostCreateView,PostUpdateView,
PostDeleteView,UserPostListView,SearchPostListView,CategoryView, download)
from django.urls import include
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

app_name = "tenders"

urlpatterns = [   
    path('',  PostListView.as_view(), name = 'index'),
    path('user/<str:username>/',  UserPostListView.as_view(), name = 'user-posts'),
    path('<int:pk>', PostDetailView.as_view(), name = 'detail'),
    path('addnew', PostCreateView.as_view(), name ='addnew'),
    path('<int:pk>/update', PostUpdateView.as_view(), name ='update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name ='delete'),
    path('result', SearchPostListView.as_view(), name ='search'),
    path('<str:cats>', CategoryView, name='category'),
   url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

tenders/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from notifications.models import Notification
from django.db.models.signals import post_save
# Create your models here.

class Catagory(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class tenders(models.Model):
    title = models.CharField(max_length = 200)
    body = RichTextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now) 
    company = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length = 200, default = 'tech', null=True, blank=True)
    open_date = models.DateField() 
    close_date = models.DateField() 
    document = models.FileField(upload_to='media', default = 'todo.txt' )
  

    
    

    def user_post(sender, instance, *args, **kwargs):
        ten = instance
        title = ten.title
        text_preview = ten.body[:90]
        sender = ten.company
        notify = Notification(title=title, sender=sender, text_preview=text_preview ,notification_type=1)
        notify.save()


   

#Post
post_save.connect(tenders.user_post, sender=tenders)

tenders/forms.py
from .models import tenders, Catagory
from django import forms
#from ckeditor.fields import RichTextField

choices = Catagory.objects.all().values_list('name', 'name')
choice_list = []
for item in choices:
    choice_list.append(item)

class TendersForm(forms.ModelForm):
    class Meta:
        model = tenders
        fields = ('title', 'category', 'company','body', 'open_date','close_date','document')



        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'company': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choice_list,attrs={'class': 'form-control'}),
            'open_date':forms.DateTimeInput(attrs={'class': 'form-control','data-target': 'datetimepicker'}),
            'close_date':forms.DateTimeInput(attrs={'class': 'form-control datetimepicker-input','data-target': '#datetimepicker1'}),
            
        }


#class UploadFileForm(forms.Form):
    #title = forms.CharField(max_length=50)
    #file = forms.FileField()


    

tenders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import HttpResponse
from .models import tenders, Catagory
import datetime
from django.core.paginator import Paginator
#from .forms import TendersSearchForm
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (ListView,
DetailView,
CreateView,
UpdateView,DeleteView)
from django import forms
from .forms import TendersForm
from django.core.files.storage import FileSystemStorage 

# Imaginary function to handle an uploaded file.
#from somewhere import handle_uploaded_file



class PostCreateView(LoginRequiredMixin,CreateView):
    model = tenders
    form_class = TendersForm   
    success_url = '../tenders'
    context={'file':tenders.objects.all()}

def download(request,path):
	file_path=os.path.join(settings.MEDIA_ROOT,path)
	if os.path.exists(file_path):
		with open(file_path,'rb')as fh:
			response=HttpResponse(fh.read(),content_type="application/document")
			response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
			return response

	raise Http404		








'''
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'tenders_form.html', {'form': form})
'''







class PostListView(ListView):
    model = tenders
    template_name = 'tenders/tenders.html'
    context_object_name = 'posts'
    cats = Catagory.objects.all()
    ordering = ['-date_posted']
    paginate_by = 4

    def get_context_data(self, *args, **kwargs):
        cat_menu = Catagory.objects.all()
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context




class UserPostListView(ListView):
    model = tenders
    template_name = 'tenders/user_posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return tenders.objects.filter(company=user).order_by('-date_posted')



class SearchPostListView(ListView):
    model = tenders
    template_name = 'tenders/search.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = tenders.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
       # users = User.objects.filter(Q(username__icontains=query))

        return object_list



class PostDetailView(DetailView):
    model = tenders


class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = tenders
    fields = ['title','company','body','open_date','close_date' ]
            
    widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'open_date':forms.DateTimeInput(attrs={'class': 'form-control','data-target': 'datetimepicker'}),
            'close_date':forms.DateTimeInput(attrs={'class': 'form-control datetimepicker-input','data-target': '#datetimepicker1'}),
            
        }
    success_url = '../'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.company:
            return True
        return False


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = tenders
    success_url = '../'
    
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.company:
            return True
        return False

 

def CategoryView (request, cats):
    
    category_tenders = tenders.objects.filter(category = cats)  

    return render(request, 'tenders/categories.html', {'cats': cats, 'category_tenders':category_tenders})

templates/tenders/addtenders.html
{% extends 'base/base.html' %}

{% block content %}


{% endblock %}

templates/tenders/catagory.html
{% extends 'base/base.html' %}
{% block content %}





<center> <h4 class="mb-3"> Total Posts by {{ view.kwargs.username }} are ({{ page_obj.paginator.count}})</h4></center>

<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        {% for post in posts %}
        <div class="col-md-12">
          <h3 ><a class="article-title" href="{% url 'tenders:detail' post.id %}" >{{post.title}}</a></h3>

            <p>By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a> on {{ post.date_posted }}</p>
          <!--  <p class="article-content">{{ post.body }}</p> -->
           
          </div>
          {% endfor %}


          <!---PAGINATION STARTS HERE-->
          {% if is_paginated %}
          
          {% if page_obj.has_previous %}

            <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>

            {% endif %}

            {% for num in page_obj.paginator.page_range %}
               {% if page_obj.number == num %}

              <a class = "btn btn-info mb-4" href="?page= {{ num }}">{{ num }}</a>

              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:' 3' %}
              <a class = "btn btn-outline-info mb-4" href="?page= {{ num }}">{{ num }}</a>
              {% endif %}

            
            {% endfor %}

            {% if page_obj.has_next %}

            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">last</a>

            {% endif %}


            {% endif %}


         

          <!--PAGINATION ENDS HERE-->
        </div>
      </div>
    </div>
  </div>   
 
  </div>   



{% endblock %}

templates/tenders/categories.html
{% extends 'base/base.html' %}
{% block content %}


   <div style="height: 113px;"></div>

<div class="unit-5 overlay" style="background-image: url('../../media/cv.jpg');">
  <div class="container text-center">
    <h2 class="mb-0">Category</h2>
    <p class="mb-0 unit-6"><a href="{% url 'Home:index' %}">Home</a> <span class="sep">></span> <span>Tender</span></p>
  </div>
</div>




<!--<center> <h4 class="mb-3"> Total Posts ({{ page_obj.paginator.count}})</h4></center>-->


<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        {% if category_tenders %}
        {% for post in category_tenders %}
        <div class="col-md-12">
          <h3 ><a class="article-title" href="{% url 'tenders:detail' post.id %}" >{{post.title}}</a></h3>

          
              By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a> on {{ post.date_posted }}</p>
          <!--  <p class="article-content">{{ post.body }}</p> -->
           
          </div>
     

          {% endfor %}
          {% else %}
          <h2>sorry this category doesnt exist!!</h2>

          {% endif %}

          <!---PAGINATION STARTS HERE-->
          {% if is_paginated %}
          
          {% if page_obj.has_previous %}

            <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>

            {% endif %}

            {% for num in page_obj.paginator.page_range %}
               {% if page_obj.number == num %}

              <a class = "btn btn-info mb-4" href="?page= {{ num }}">{{ num }}</a>

              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:' 3' %}
              <a class = "btn btn-outline-info mb-4" href="?page= {{ num }}">{{ num }}</a>
              {% endif %}

            
            {% endfor %}

            {% if page_obj.has_next %}

            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">last</a>

            {% endif %}


            {% endif %}


         

          <!--PAGINATION ENDS HERE-->
        </div>
      </div>
    </div>
  </div>   
 
  </div>   


{% endblock %}

templates/tenders/search.html
{% extends 'base/base.html' %}
{% block content %}

<div class="container">
    <div class="row align-items-center">
      <div class="col-12" data-aos="fade">
        <h1>Find Tenders</h1>


        <form method="GET" action="{% url 'tenders:search' %}" value="{{request.GET.q}}">
          <div class="row mb-3">
            <div class="col-md-9">
              <div class="row">
                <div class="col-md-6 mb-3 mb-md-0">
                  <input name="q" value="{{request.GET.q}}" type="text" class="form-control"
                    placeholder="tender title or  keywords ">
                    <input type="submit" class="btn btn-search btn-primary btn-block" value="Search">
                </div>

              </div>
            </div>
           
          </div>


        </form>


      </div>
    </div>
  </div>

<div class="container">
    <div class="row">
      <div class="col-md-12 card mb-4  mt-3 ">
        <div class="card-body">
<h1>Search results</h1>


<h5> Results for <b> {{request.GET.q}} </b></h5>
{% if object_list == posts %}
<ul>
    {% for post in object_list %}
      <li>
        <div class="col-md-12">
            <h3 ><a class="article-title" href="{% url 'tenders:detail' post.id %}" >{{post.title}}</a></h3>
  
            
                By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a> on {{ post.date_posted }}</p>
            <!--  <p class="article-content">{{ post.body }}</p> -->
             
            </div>
      </li>
    {% endfor %}
  </ul>
  {% else %}

<P>No search reuslts for this query</P>

{%  endif %}

</div>
</div>
</div>
</div>
<!--
{% if submitbutton == request.GET.q != " " %}

<h5> Results for <b> {{request.GET.q}} </b></h5>
{% if results == posts %}

    {% for post in object_list %}

    {{post.title}}
</br>

    {% endfor %}
{% else %}

<P>No search reuslts for this query</P>

{%  endif %}
{% endif %}



-->
{% endblock %}

templates/tenders/tenders.html
{% extends 'base/base.html' %}
{% block content %}


<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12" data-aos="fade">
            <h1>Find Tenders</h1>


            <form method="GET" action="{% url 'tenders:search' %}" value="{{request.GET.q}}">
              <div class="row mb-3">
                <div class="col-md-9">
                  <div class="row">
                    <div class="col-md-6 mb-3 mb-md-0">
                      <input name="q" value="{{request.GET.q}}" type="text" class="form-control"
                        placeholder="tender title or  keywords ">
                        <input type="submit" class="btn btn-search btn-primary btn-block" value="Search">
                    </div>

                  </div>
                </div>
               
              </div>


            </form>


          </div>
        </div>
      </div>


      <div class="site-section bg-light">
        <div class="container">
          <div class="row">
            <div class="col-md-8 mb-5 mb-md-0" data-aos="fade-up" data-aos-delay="100">
              <h2 class="mb-5 h3">Categories</h2>
              <div class="rounded border jobs-wrap">



                <!--Categories Start-->

                {% for item in cat_menu %}

                <a href="{% url 'tenders:category' item%}"
                  class="job-item d-block d-md-flex align-items-center  border-bottom fulltime">

                  <div class="job-details h-100">
                    <div class="p-3 align-self-center">
                      <h3>{{ item }}</h3>

                    </div>
                  </div>
                </a>
                {% endfor %}



              </div>
            </div>

            <!--Categories Start-->

            <!--Featured Tenders-->





            <div class="col-md-4 block-16" data-aos="fade-up" data-aos-delay="200">
              <div class="d-flex mb-0">
                <h2 class="mb-5 h3 mb-0">Featured Tenders</h2>
                <div class="ml-auto mt-1"><a href="#" class="owl-custom-prev">Prev</a> / <a href="#"
                    class="owl-custom-next">Next</a></div>
              </div>

              <div class="nonloop-block-16 owl-carousel">
                {% for post in posts %}
                <div class="border rounded p-4 bg-white">

                  <h2 class="h5">{{post.title }}</h2>
                 
                  <p>
                    <span class="d-block"><span class="icon-suitcase"></span> By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a></span>
                    <span class="d-block"><span class="icon-room"></span> Category<a href="{% url 'tenders:category' post.category%}"> {{ post.category }}</a></span>
                    <span class="d-block"><span class="icon-money mr-1"></span>  {{ post.date_posted }} <br/> Bid open - {{ post.open_date }}<br/>
                    Bid Close - {{post.close_date}}</p></span>
                  </p>
                  <p class="mb-0"></p>
                </div>
                {% endfor %}

              </div>
            </div>
          </div>
        </div>
      </div>

      <!--TEnders-->
    </div>
  </div>
</div>

<center>
  <h4 class="mb-3"> Total Posts ({{page_obj.paginator.count}})</h4> 

  {% for post in posts %}
  <a href="{% url 'tenders:user-posts' post.company.username %}"> My Tenders</a>
  {% endfor %}



</center>


<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        {% for post in posts %}
        
        <div class="col-md-12">
          <h3><a class="article-title" href="{% url 'tenders:detail' post.id %}">{{post.title}}</a></h3>
          <p>Category<a href="{% url 'tenders:category' post.category%}"> {{ post.category }}</a>
            By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a> on
            {{ post.date_posted }} <br/>
            Bid open - {{ post.open_date }}<br/>
            Bid Close - {{post.close_date}}</p>
          <!--  <p class="article-content">{{ post.body }}</p> -->

        </div>
        {% endfor %}


        <!---PAGINATION STARTS HERE-->
        {% if is_paginated %}

        {% if page_obj.has_previous %}

        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>

        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}

        <a class="btn btn-info mb-4" href="?page= {{ num }}">{{ num }}</a>

        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:' 3' %}
        <a class="btn btn-outline-info mb-4" href="?page= {{ num }}">{{ num }}</a>
        {% endif %}


        {% endfor %}

        {% if page_obj.has_next %}

        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">last</a>

        {% endif %}
        {% endif %}
       <!--PAGINATION ENDS HERE-->
      </div>
    </div>
  </div>
</div>

</div>

{% endblock %}

templates/tenders/tenders_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}


<div class="container">
    <div class="row">
      <div class="row mb-3">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-6 mb-3 mb-md-0">
       <span class="cen"> <h4 class="mb-0 site-logo">Delete <strong class="font-weight-bold"> Tender</strong>  </h4></span>  
              <form method="POST" class="p-5 bg-white">
                <div class="row form-group">
                 
                  <div class="col-md-12 mb-3 mb-md-0">
  
                    {% csrf_token %}
                    <fieldset class="form-group">
                      

               <h2> Are you sure you want to delete the post "{{object.title}}"</h2>
            
                      
                    </fieldset>
                    <div class="form-group">
                      <button class="bg-warning text-white py-3 px-4 rounded" class="icon-plus mr-3" type="submit" value="submit"> Yes, Delete</button>
                      <a class="bg-secondary text-white py-3 px-4 rounded" class="icon-plus mr-3" href = "../" > Cancel</a>
                    
                    </div>
                  </div>
                </div>
  
              </form>
            
  
            </div>
  
  
  
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  
{% endblock %}

templates/tenders/tenders_detail.html
{% extends 'base/base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        <div class="form-group">
        

          {% if object.company == user %}
          <a class="bg-secondary text-white py-1 px-1 rounded" class="icon-plus mr-3" href = "{% url 'tenders:update' object.id %}" > Update</a> 
          <a class="bg-danger text-white py-1 px-1 rounded" class="icon-plus mr-3" href = "{% url 'tenders:delete' object.id %}" > Delete</a>
       {% endif %}
        </div>
        <div class="col-md-12">
          <h1 class="article-title">{{ object.title }}</h1>
          <p>By  <a href="">{{ object.company }}</a> on {{ object.date_posted }}</p>
          <p>{{ object.body|safe }}</p>
         
	<button class = "bg-warning py-3 px-4 rounded" class="icon-plus mr-3"><a class ="text-black" href="{{object.document.url}}" download="{{object.document.url}}">Download</a></button>

        </div>
      

      </div>
    </div>
  </div>
</div>

</div>



{% endblock %}

templates/tenders/tenders_form.html
{% extends 'base/base.html' %}

{% block content %}


       <span class="cen"> <h4 class="mb-0 site-logo">Post New <strong class="font-weight-bold"> Tender</strong>  </h4></span>  
       <div class="form-group">
              
       <form method="POST" class="p-5 bg-white">
       
  
                    {% csrf_token %}

                    {{ form.media }}
                    {{ form.as_p }}
                    
                                    
                      <button class="bg-primary text-white py-3 px-4 rounded" class="icon-plus mr-3" type="submit" value="submit"> Post</button>
                   </form>
                    </div>
                  </div>
                </div>
  
              
            
  
            </div>
      </div>
  
  
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  
{% endblock %}

templates/tenders/user_posts.html
{% extends 'base/base.html' %}
{% block content %}





<center> <h4 class="mb-3"> Total Posts by {{ view.kwargs.username }} are ({{ page_obj.paginator.count}})</h4></center>

<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        {% for post in posts %}
        <div class="col-md-12">
          <h3 ><a class="article-title" href="{% url 'tenders:detail' post.id %}" >{{post.title}}</a></h3>

            <p>By <a href="{% url 'tenders:user-posts' post.company.username %}">{{ post.company }}</a> on {{ post.date_posted }}</p>
          <!--  <p class="article-content">{{ post.body }}</p> -->
           
          </div>
          {% endfor %}


          <!---PAGINATION STARTS HERE-->
          {% if is_paginated %}
          
          {% if page_obj.has_previous %}

            <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>

            {% endif %}

            {% for num in page_obj.paginator.page_range %}
               {% if page_obj.number == num %}

              <a class = "btn btn-info mb-4" href="?page= {{ num }}">{{ num }}</a>

              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:' 3' %}
              <a class = "btn btn-outline-info mb-4" href="?page= {{ num }}">{{ num }}</a>
              {% endif %}

            
            {% endfor %}

            {% if page_obj.has_next %}

            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">last</a>

            {% endif %}


            {% endif %}


         

          <!--PAGINATION ENDS HERE-->
        </div>
      </div>
    </div>
  </div>   
 
  </div>   



{% endblock %}