AddisTender/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_view
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('tenders/', include('tenders.urls')),
    path('register/', user_view.register, name = 'register' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'Login' ),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'Logout' ),  
    path('profile/', user_view.profile, name = 'profile' ),
    path('noti/', include('notifications.urls')),
    path('chat/', include('chat.urls')),
    path('payment/', include('payment.urls')), 

   
   
  
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, email
# from .views import detail
from django.urls import include

app_name = "Home"

urlpatterns = [
    path('', home, name = 'index'),
       path('email/', email, name = "email"),
]

payment/urls.py
from django.urls import path
from .views import pay, charge, successMsg

app_name = "payment"


urlpatterns = [
    path('', pay, name = "pay"),
    path('charge/', charge, name = "charge"),
    path('success/<str:args>/', successMsg, name = "success"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse

import stripe

stripe.api_key = "sk_test_51HuDtaLLRgPcFpZt1watXvelSray78T6uyh3kuVTW8JPe9HAEYuxnkn2lWt8OSs3t3o7hYzmJ2hDp2KzZbO4yv6W00loVvVF40"

# Create your views here.

def pay(request):
	return render(request, 'payment/index.html')


def charge(request):
	amount = 5
	if request.method == 'POST':
		print('Data:', request.POST)

		amount = int(request.POST['amount'])

		customer = stripe.Customer.create(
			email=request.POST['email'],
			name=request.POST['FullName'],
			source=request.POST['stripeToken']
			)
		charge = stripe.Charge.create(
			customer=customer,
			amount=amount*100,
			currency='usd',
			description="Payment"
			)

	return redirect(reverse('payment:success', args=[amount]))


def successMsg(request, args):
	amount = args
	return render(request, 'payment/success.html', {'amount':amount})

templates/Payment/index.html
{% extends 'payment/template.html' %}
{% load static %}
{% block content %}
	<style type="text/css">
		/**
		 * The CSS shown here will not be introduced in the Quickstart guide, but shows
		 * how you can use CSS to style your Element's container.
		 */
		.StripeElement {
		  box-sizing: border-box;

		  height: 40px;

		  padding: 10px 12px;

		  border: 1px solid transparent;
		  border-radius: 4px;
		  background-color: white;

		  box-shadow: 0 1px 3px 0 #e6ebf1;
		  -webkit-transition: box-shadow 150ms ease;
		  transition: box-shadow 150ms ease;
		}

		.StripeElement--focus {
		  box-shadow: 0 1px 3px 0 #cfd7df;
		}

		.StripeElement--invalid {
		  border-color: #f02b04;
		}

		.StripeElement--webkit-autofill {
		  background-color: #fefde5 !important;
		}
	</style>


	<script src="https://js.stripe.com/v3/"></script>


	<div class="column-6">
	<div class="container">
	  <div class="left-wrapper">
  
		<div class="col-md-12 col-lg-8 mb-5">
		
  
			<button class="backButton" type="submit"><a href="{% url 'Home:index' %}" >Back</a></button>
		  
  
		</div>
	  </div>
	</div>
  </div>
  
	

	<div id="container">
		<div class="column-6">
			<div id="left-wrapper">
				<img id="profile-pic" src="{{user.profile.image.url}}">
				<div id="left-wrapper-header">
					<!-- <h3>Payment</h3> -->
					<!-- <h5>One Time Donation</h5> -->
				</div>
				<div style="clear:left"></div>
				<hr>
				<!-- Add form here -->
				<form action="{% url 'payment:charge' %}" method="post" id="payment-form">
					{% csrf_token %}
					<div class="form-field-12">
						<label for="amount">Choose Amount:</label>
						<br>
						<br>
						<select required name="amount" id="amount">
						  <option selected value="5">$5 For One Month</option>
						  <option value="10">$10 For One Year</option>
						  <!-- <option value="25">$25 --- I love your channel!</option> -->
						</select>
					</div>

					<div class="form-field-6">
						<input required type="text" name="email" placeholder="Email...">
					</div>

					<div class="form-field-6">
						<input required type="text" name="FullName" placeholder="Full Name...">
					</div>

				  <div class="form-row">
				    <label for="card-element">
				      Credit or debit card
				    </label>
				    <div id="card-element">
				      <!-- A Stripe Element will be inserted here. -->
				    </div>

				    <!-- Used to display form errors. -->
				    <div id="card-errors" role="alert"></div>
				  </div>
				  
				  <div style="clear:left"></div>
				  <hr>

				 	<input  class="myButton" style="background-color:#188302" type="submit" value="Submit Payment" name="">

				</form>

			
			</div>
		</div>

		<div class="column-6">
			<!-- <div id="right-wrapper">

				<img class="coffee-cup" src="{% static 'images/Coffee5.png' %}">
				<img class="coffee-cup2" src="{% static 'images/Coffee10.png' %}">
				<img class="coffee-cup3" src="{% static 'images/Coffee25.png' %}">
				<h3>If I've provided you with value please consider supporting our efforts ;)</h3>

				<p>Source code and videos are free to download, use as you wish :) At no point should you feel obligated to donate but if you have the means consider the time and effort I put into each project/video. Thank you!</p>
				<hr>
				<a href="https://github.com/divanov11/buydenniscoffee" target="_blank" class="myButton">Download source code</a>
			</div> -->
		</div>
	</div>






	<script>
		// Create a Stripe client.
		var stripe = Stripe('pk_test_51HuDtaLLRgPcFpZtHrP9fW5ty0y05NwxE7SCOaYX7OanCEbOVQ0IHxR6djbPjJJK1QzOuyiio0Jqv65hfXw3XOoR00TQGKevZu');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4'
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
	</script>
	
{% endblock content %}

templates/Payment/success.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
	<div id="box">
		<img id="succes-icon" src="{{user.profile.image.url}}">
		<h4>Thank you for your Payment of ${{amount}}!</h4>
		<p>Your support aspiring Tenders around the world! You should receive a receipt to the email you provided shortly :)</p>
		<hr>
	
	</div>

{% endblock content %}

templates/Payment/template.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Addis Tender</title>

	<link href="https://fonts.googleapis.com/css?family=Fjalla+One|Inter&display=swap" rel="stylesheet">

	<!-- Landing page styling -->
	<style type="text/css">

		body{
			background-color: #F8F8F8;
		}

		h3, h5{
			font-family: 'Fjalla One', sans-serif;
			font-weight: 100;
		}

		h3{
			font-size: 36px;
		}

		h5{
			font-size: 24px;
		}

		p, label{
			font-family: 'Inter', sans-serif;
		}

		hr{
			color:#fff;
			background-color: #fff;
			border-top:1px solid #fff;
			margin-top:20px;
			margin-bottom: 20px;
		}

		#container{
			width:1200px;
			margin:0 auto;
			padding-top: 1%;
		}

		.column-6{
			width: 50%;
			/* float:left; */
			max-width: 1000px;
  			margin: auto;
		}

		#left-wrapper{
			background-color: #e9e7e7;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    border-radius: 4px;
		    border: 1px solid transparent;
		    padding: 30px;	
		}

		#right-wrapper{
			padding: 30px;
		}

		#profile-pic{
			width:280px;
			display:block;
			margin: 0 auto;
			border-radius: 50%;
			/* float:left; */

		}

		#left-wrapper-header{
			min-width:50%;
			float:left;
			padding-left:20px;

		}

		#left-wrapper-header h3{
			color:#fff;

		}

		#right-wrapper h3{
			color: #10a195;
		}

		.coffee-cup{
			margin-left: 20px;
			width: 100px;
		}

		.coffee-cup2{
			margin-left: 20px;
			width: 150px;
		}

		.coffee-cup3{
			margin-left: 20px;
			width: 200px;
		}

		/* ------------------------ FORM FIELDS ------------------------ */

		.form-field-12{
			width: 100%;
			margin-bottom: 10px;
			padding-top: 5px;
		}

		.form-field-6{
			width: 50%;
			float:left;
			margin-bottom: 10px;
		}

		select{
			width: 100%;
			height: 60px!important;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    padding: 10px 12px;
		    border-radius: 4px;
		    background-color: #fff;
		    border: 1px solid transparent;
		    font-size: 20px;
		    color:	#44464a;
		}

		input{
		    box-shadow: 0 1px 3px 0 #dce0e6;
		    height:40px;
		    border-radius: 4px;
		    background-color: #fff;
		    border: 1px solid transparent;
		    color:	#44464a;
		    width: 95%;
		    padding: 5px;
		    font-size: 16px;

		}

		input::placeholder {
		  color: #9fa1a6;
		}

		/* ------------------------ BUTTON STYLING ------------------------ */
		.myButton {
			background-color:#72cca7;
			display:inline-block;
			cursor:pointer;
			color:#ffffff;
			font-family:Verdana;
			font-size:17px;
			padding:10px;
			width:100%;
			border-radius: 0;
			text-decoration:none;
			text-align: center;
			transition: .3s;
		}
		.myButton:hover {
			opacity: .6;
		}

		@media screen and (max-width:1200px){
			#container{
				width:80%;
			}

			.column-6{
				width: 100%;
			}
		}

		@media screen and (max-width:800px){
			#container{
				width:100%;
			}

			.coffee-cup{
				margin-left: 20px;
				width: 50px;
			}

			.coffee-cup2{
				margin-left: 20px;
				width: 75px;
			}

			.coffee-cup3{
				margin-left: 20px;
				width: 100px;
			}

		}
	</style>

	<!-- Success page styling -->
	<style type="text/css">
		h4{
			font-family: 'Fjalla One', sans-serif;
			font-weight: 100;
			font-size: 24px;
		}

		#box{
			max-width: 500px;
			margin:0 auto;
			margin-top: 100px;
			padding:30px;
			background-color: #fff;
			text-align: center;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    border-radius: 4px;
		    border: 1px solid transparent;
		}

		.myButton {
			background-color:#188302;
			display:inline-block;
			cursor:pointer;
			color:#ffffff;
			font-family:Verdana;
			font-size:17px;
			padding:10px;
			width:100%;
			border-radius: 0;
			text-decoration:none;
			text-align: center;
			transition: .3s;
		}
		.myButton:hover {
			opacity: .6;
		}

		#succes-icon{
			width: 100px;

		}


		.backButton {
			background-color:#09b935;
			display:inline-block;
			cursor:pointer;
			color:#000;
			font-family:Verdana;
			font-size:17px;
			padding:10px;
			width:40%;
			border-radius: 0;
			text-decoration:none;
			text-align: center;
			transition: .3s;
		}
		.backButton:hover {
			opacity: .6;
		}



	</style>
</head>
<body>
	{% block content %}

	{% endblock content %}
</body>
</html>